# Generated by Django 3.1 on 2020-09-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('Calificacion', models.CharField(max_length=300)),
                ('imagen', models.CharField(max_length=4000)),
                ('CortaDescriocion', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
