# Generated by Django 3.1 on 2020-09-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='CortaDescriocion',
            new_name='CortaDescripcion',
        ),
    ]
