# Generated by Django 3.1 on 2020-09-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0003_remove_peliculas_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='Calificacion',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
