# Generated by Django 3.1 on 2020-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0004_peliculas_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
