# Generated by Django 3.1 on 2020-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20200918_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=1000)),
                ('Usuario', models.CharField(max_length=1000)),
            ],
        ),
    ]
